#pragma once

/**
 * Arduino / non-menuconfig defaults for the full vendored ESP-DL model zoo.
 * Models load from VFS: {mount}/models/p4/*.espdl
 * See models/espdl/p4/ and models/espdl/README.md.
 */

#ifndef CONFIG_BSP_SD_MOUNT_POINT
#define CONFIG_BSP_SD_MOUNT_POINT "/sdcard"
#endif

/* ---- model location: SD card for all (Arduino) ---- */
#ifndef CONFIG_HUMAN_FACE_DETECT_MODEL_IN_SDCARD
#define CONFIG_HUMAN_FACE_DETECT_MODEL_IN_SDCARD 1
#endif
#ifndef CONFIG_HUMAN_FACE_FEAT_MODEL_IN_SDCARD
#define CONFIG_HUMAN_FACE_FEAT_MODEL_IN_SDCARD 1
#endif
#ifndef CONFIG_COCO_DETECT_MODEL_IN_SDCARD
#define CONFIG_COCO_DETECT_MODEL_IN_SDCARD 1
#endif
#ifndef CONFIG_PEDESTRIAN_DETECT_MODEL_IN_SDCARD
#define CONFIG_PEDESTRIAN_DETECT_MODEL_IN_SDCARD 1
#endif
#ifndef CONFIG_CAT_DETECT_MODEL_IN_SDCARD
#define CONFIG_CAT_DETECT_MODEL_IN_SDCARD 1
#endif
#ifndef CONFIG_DOG_DETECT_MODEL_IN_SDCARD
#define CONFIG_DOG_DETECT_MODEL_IN_SDCARD 1
#endif
#ifndef CONFIG_HAND_DETECT_MODEL_IN_SDCARD
#define CONFIG_HAND_DETECT_MODEL_IN_SDCARD 1
#endif
#ifndef CONFIG_HAND_GESTURE_CLS_MODEL_IN_SDCARD
#define CONFIG_HAND_GESTURE_CLS_MODEL_IN_SDCARD 1
#endif
#ifndef CONFIG_COCO_POSE_MODEL_IN_SDCARD
#define CONFIG_COCO_POSE_MODEL_IN_SDCARD 1
#endif
#ifndef CONFIG_COCO_SEG_MODEL_IN_SDCARD
#define CONFIG_COCO_SEG_MODEL_IN_SDCARD 1
#endif
#ifndef CONFIG_IMAGENET_CLS_MODEL_IN_SDCARD
#define CONFIG_IMAGENET_CLS_MODEL_IN_SDCARD 1
#endif
#ifndef CONFIG_PERSON_REID_FEAT_MODEL_IN_SDCARD
#define CONFIG_PERSON_REID_FEAT_MODEL_IN_SDCARD 1
#endif
#ifndef CONFIG_PP_OCR_V6_MODEL_IN_SDCARD
#define CONFIG_PP_OCR_V6_MODEL_IN_SDCARD 1
#endif
#ifndef CONFIG_SPEAKER_VERIFICATION_MODEL_IN_SDCARD
#define CONFIG_SPEAKER_VERIFICATION_MODEL_IN_SDCARD 1
#endif

/* ---- SD relative dirs ---- */
#define ESP32P4_ESPDL_SD_DIR "models/p4"

#ifndef CONFIG_HUMAN_FACE_DETECT_MODEL_SDCARD_DIR
#define CONFIG_HUMAN_FACE_DETECT_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_HUMAN_FACE_FEAT_MODEL_SDCARD_DIR
#define CONFIG_HUMAN_FACE_FEAT_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_COCO_DETECT_MODEL_SDCARD_DIR
#define CONFIG_COCO_DETECT_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_PEDESTRIAN_DETECT_MODEL_SDCARD_DIR
#define CONFIG_PEDESTRIAN_DETECT_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_CAT_DETECT_MODEL_SDCARD_DIR
#define CONFIG_CAT_DETECT_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_DOG_DETECT_MODEL_SDCARD_DIR
#define CONFIG_DOG_DETECT_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_HAND_DETECT_MODEL_SDCARD_DIR
#define CONFIG_HAND_DETECT_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_HAND_GESTURE_CLS_MODEL_SDCARD_DIR
#define CONFIG_HAND_GESTURE_CLS_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_COCO_POSE_MODEL_SDCARD_DIR
#define CONFIG_COCO_POSE_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_COCO_SEG_MODEL_SDCARD_DIR
#define CONFIG_COCO_SEG_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_IMAGENET_CLS_MODEL_SDCARD_DIR
#define CONFIG_IMAGENET_CLS_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_PERSON_REID_FEAT_MODEL_SDCARD_DIR
#define CONFIG_PERSON_REID_FEAT_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_PP_OCR_V6_MODEL_SDCARD_DIR
#define CONFIG_PP_OCR_V6_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_SPEAKER_VERIFICATION_MODEL_SDCARD_DIR
#define CONFIG_SPEAKER_VERIFICATION_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif
#ifndef CONFIG_ESP_DL_RECOGNITION_MODEL_SDCARD_DIR
#define CONFIG_ESP_DL_RECOGNITION_MODEL_SDCARD_DIR ESP32P4_ESPDL_SD_DIR
#endif

/* ---- defaults (enum 0) ---- */
#ifndef CONFIG_DEFAULT_HUMAN_FACE_DETECT_MODEL
#define CONFIG_DEFAULT_HUMAN_FACE_DETECT_MODEL 0
#endif
#ifndef CONFIG_DEFAULT_HUMAN_FACE_FEAT_MODEL
#define CONFIG_DEFAULT_HUMAN_FACE_FEAT_MODEL 0
#endif
#ifndef CONFIG_DEFAULT_COCO_DETECT_MODEL
#define CONFIG_DEFAULT_COCO_DETECT_MODEL 0
#endif
#ifndef CONFIG_DEFAULT_PEDESTRIAN_DETECT_MODEL
#define CONFIG_DEFAULT_PEDESTRIAN_DETECT_MODEL 0
#endif
#ifndef CONFIG_DEFAULT_CAT_DETECT_MODEL
#define CONFIG_DEFAULT_CAT_DETECT_MODEL 0
#endif
#ifndef CONFIG_DEFAULT_DOG_DETECT_MODEL
#define CONFIG_DEFAULT_DOG_DETECT_MODEL 0
#endif
#ifndef CONFIG_DEFAULT_HAND_DETECT_MODEL
#define CONFIG_DEFAULT_HAND_DETECT_MODEL 0
#endif
#ifndef CONFIG_DEFAULT_HAND_GESTURE_CLS_MODEL
#define CONFIG_DEFAULT_HAND_GESTURE_CLS_MODEL 0
#endif
#ifndef CONFIG_DEFAULT_COCO_POSE_MODEL
#define CONFIG_DEFAULT_COCO_POSE_MODEL 0
#endif
#ifndef CONFIG_DEFAULT_COCO_SEG_MODEL
#define CONFIG_DEFAULT_COCO_SEG_MODEL 0
#endif
#ifndef CONFIG_DEFAULT_IMAGENET_CLS_MODEL
#define CONFIG_DEFAULT_IMAGENET_CLS_MODEL 0
#endif
#ifndef CONFIG_DEFAULT_PERSON_REID_FEAT_MODEL
#define CONFIG_DEFAULT_PERSON_REID_FEAT_MODEL 0
#endif
#ifndef CONFIG_DEFAULT_PP_OCR_V6_REC_MODEL
#define CONFIG_DEFAULT_PP_OCR_V6_REC_MODEL 0
#endif
#ifndef CONFIG_PP_OCR_V6_REC_MODE
#define CONFIG_PP_OCR_V6_REC_MODE 0
#endif
#ifndef CONFIG_DEFAULT_SPEAKER_VERIFICATION_MODEL
#define CONFIG_DEFAULT_SPEAKER_VERIFICATION_MODEL 0
#endif

/* ---- flash flags (Arduino uses SD; keep 1 so load_model #if passes) ---- */
#ifndef CONFIG_FLASH_HUMAN_FACE_DETECT_MSRMNP_S8_V1
#define CONFIG_FLASH_HUMAN_FACE_DETECT_MSRMNP_S8_V1 1
#endif
#ifndef CONFIG_FLASH_ESPDET_PICO_224_224_FACE
#define CONFIG_FLASH_ESPDET_PICO_224_224_FACE 1
#endif
#ifndef CONFIG_FLASH_ESPDET_PICO_416_416_FACE
#define CONFIG_FLASH_ESPDET_PICO_416_416_FACE 1
#endif
#ifndef CONFIG_FLASH_HUMAN_FACE_FEAT_MFN_S8_V1
#define CONFIG_FLASH_HUMAN_FACE_FEAT_MFN_S8_V1 1
#endif
#ifndef CONFIG_FLASH_HUMAN_FACE_FEAT_MBF_S8_V1
#define CONFIG_FLASH_HUMAN_FACE_FEAT_MBF_S8_V1 1
#endif
#ifndef CONFIG_FLASH_COCO_DETECT_YOLO11N_S8_V1
#define CONFIG_FLASH_COCO_DETECT_YOLO11N_S8_V1 1
#endif
#ifndef CONFIG_FLASH_COCO_DETECT_YOLO11N_320_S8_V1
#define CONFIG_FLASH_COCO_DETECT_YOLO11N_320_S8_V1 1
#endif
#ifndef CONFIG_FLASH_PEDESTRIAN_DETECT_PICO_S8_V1
#define CONFIG_FLASH_PEDESTRIAN_DETECT_PICO_S8_V1 1
#endif
#ifndef CONFIG_FLASH_ESPDET_PICO_224_224_CAT
#define CONFIG_FLASH_ESPDET_PICO_224_224_CAT 1
#endif
#ifndef CONFIG_FLASH_ESPDET_PICO_416_416_CAT
#define CONFIG_FLASH_ESPDET_PICO_416_416_CAT 1
#endif
#ifndef CONFIG_FLASH_ESPDET_PICO_224_224_DOG
#define CONFIG_FLASH_ESPDET_PICO_224_224_DOG 1
#endif
#ifndef CONFIG_FLASH_ESPDET_PICO_416_416_DOG
#define CONFIG_FLASH_ESPDET_PICO_416_416_DOG 1
#endif
#ifndef CONFIG_FLASH_ESPDET_PICO_224_224_HAND
#define CONFIG_FLASH_ESPDET_PICO_224_224_HAND 1
#endif
#ifndef CONFIG_FLASH_HAND_GESTURE_CLS_MOBILENETV2_0_5_S8_V1
#define CONFIG_FLASH_HAND_GESTURE_CLS_MOBILENETV2_0_5_S8_V1 1
#endif
#ifndef CONFIG_FLASH_COCO_POSE_YOLO11N_POSE_S8_V1
#define CONFIG_FLASH_COCO_POSE_YOLO11N_POSE_S8_V1 1
#endif
#ifndef CONFIG_FLASH_COCO_POSE_YOLO11N_POSE_S8_V2
#define CONFIG_FLASH_COCO_POSE_YOLO11N_POSE_S8_V2 1
#endif
#ifndef CONFIG_FLASH_COCO_SEG_YOLO11N_SEG_S8_V1
#define CONFIG_FLASH_COCO_SEG_YOLO11N_SEG_S8_V1 1
#endif
#ifndef CONFIG_FLASH_IMAGENET_CLS_MOBILENETV2_S8_V1
#define CONFIG_FLASH_IMAGENET_CLS_MOBILENETV2_S8_V1 1
#endif
#ifndef CONFIG_FLASH_PERSON_REID_FEAT_OSN_S8_V1
#define CONFIG_FLASH_PERSON_REID_FEAT_OSN_S8_V1 1
#endif
#ifndef CONFIG_FLASH_PP_OCR_V6_REC_S8
#define CONFIG_FLASH_PP_OCR_V6_REC_S8 1
#endif
#ifndef CONFIG_FLASH_PP_OCR_V6_REC_S16
#define CONFIG_FLASH_PP_OCR_V6_REC_S16 1
#endif
#ifndef CONFIG_FLASH_SPEAKER_VERIFICATION
#define CONFIG_FLASH_SPEAKER_VERIFICATION 1
#endif

/* Image pixel converters used by preprocess (RGB888 path). */
#ifndef CONFIG_PIX_CVT_RGB888_TO_RGB888_SUPPORT
#define CONFIG_PIX_CVT_RGB888_TO_RGB888_SUPPORT 1
#endif
#ifndef CONFIG_PIX_CVT_RGB565_TO_RGB888_SUPPORT
#define CONFIG_PIX_CVT_RGB565_TO_RGB888_SUPPORT 1
#endif
#ifndef CONFIG_PIX_CVT_RGB888_TO_GRAY_SUPPORT
#define CONFIG_PIX_CVT_RGB888_TO_GRAY_SUPPORT 1
#endif
